export const PRICING_PLANS = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Boshlash uchun ideal',
    price: 500,
    currency: 'USD',
    period: 'bir martalik',
    features: ['1 ta Telegram bot', 'Admin panel', '1 yil support', 'Email support'],
    cta: 'Sotib olish',
    recommended: false,
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Eng mashhur tanlov',
    price: 1000,
    currency: 'USD',
    period: 'bir martalik',
    features: [
      '3 ta Telegram bot',
      'Admin panel',
      '2 yil support',
      'Email + Telegram support',
      'Bepul yangilanishlar',
    ],
    cta: 'Sotib olish',
    recommended: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'To\'liq yechim',
    price: 2000,
    currency: 'USD',
    period: 'bir martalik',
    features: [
      'Cheksiz bot',
      'Admin panel',
      'Abadiy support',
      '24/7 support',
      'Custom xususiyatlar',
      'Bepul yangilanishlar',
    ],
    cta: 'Bog\'lanish',
    recommended: false,
  },
] as const;
