export const ErrorCodes = {
  // 400 — Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_CONTENT_ID: "INVALID_CONTENT_ID",
  INVALID_PLAN_ID: "INVALID_PLAN_ID",
  INVALID_PAYMENT_AMOUNT: "INVALID_PAYMENT_AMOUNT",
  INVALID_RATING: "INVALID_RATING",
  INVALID_DEVICE_ID: "INVALID_DEVICE_ID",

  // 401 — Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_MISSING: "TOKEN_MISSING",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // 403 — Authorization
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  PLAN_UPGRADE_REQUIRED: "PLAN_UPGRADE_REQUIRED",
  DEVICE_LIMIT_EXCEEDED: "DEVICE_LIMIT_EXCEEDED",
  CONCURRENT_STREAM_LIMIT: "CONCURRENT_STREAM_LIMIT",
  GEO_RESTRICTION: "GEO_RESTRICTION",
  AGE_RESTRICTION: "AGE_RESTRICTION",

  // 404 — Not Found
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  MOVIE_NOT_FOUND: "MOVIE_NOT_FOUND",
  SERIES_NOT_FOUND: "SERIES_NOT_FOUND",
  EPISODE_NOT_FOUND: "EPISODE_NOT_FOUND",
  SEASON_NOT_FOUND: "SEASON_NOT_FOUND",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  GENRE_NOT_FOUND: "GENRE_NOT_FOUND",
  ACTOR_NOT_FOUND: "ACTOR_NOT_FOUND",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",

  // 409 — Conflict
  CONFLICT: "CONFLICT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  SUBSCRIPTION_ALREADY_ACTIVE: "SUBSCRIPTION_ALREADY_ACTIVE",
  CONTENT_ALREADY_EXISTS: "CONTENT_ALREADY_EXISTS",

  // 422 — Business Logic
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_PROCESSING: "PAYMENT_PROCESSING",
  SUBSCRIPTION_CANCELLATION_FAILED: "SUBSCRIPTION_CANCELLATION_FAILED",
  REFUND_NOT_ALLOWED: "REFUND_NOT_ALLOWED",
  CONTENT_NOT_AVAILABLE: "CONTENT_NOT_AVAILABLE",
  DOWNLOAD_NOT_ALLOWED: "DOWNLOAD_NOT_ALLOWED",
  MAX_FAVORITES_REACHED: "MAX_FAVORITES_REACHED",

  // 429 — Rate Limit
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // 415/416 — Media/Storage
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
  TRANSCODING_FAILED: "TRANSCODING_FAILED",
  STORAGE_ERROR: "STORAGE_ERROR",

  // 502/503/504 — External
  TELEGRAM_API_ERROR: "TELEGRAM_API_ERROR",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  EXTERNAL_SERVICE_TIMEOUT: "EXTERNAL_SERVICE_TIMEOUT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // 500 — Internal
  DATABASE_ERROR: "DATABASE_ERROR",
  CACHE_ERROR: "CACHE_ERROR",
  QUEUE_ERROR: "QUEUE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
